setwd("/Users/venkatakrishnamohansunkara/Desktop/Data_Mining/Data_Mining/project/Final/")
f <- read.csv('compressed_associaton_qcut.csv')
#df <- subset(df,select = -c(X))
#Even eclat cannot handle the normal data because it tries to store the entire data in memory in some sparse representation which throws a memory
#error.
itemsets <- eclat(f,parameter = list(supp=0.1,maxlen=1000))
rules <- ruleInduction(itemsets, f, confidence = .9)
rules.sorted <- sort(rules,decreasing = TRUE, by="lift")
rules_count <- subset(rules, subset = rhs %pin% "count=" )
rules_count.sorted <- sort(rules_count,decreasing = TRUE,by="lift")
rules_protest <- subset(rules,subset = rhs %pin% "protest.category")
rules_protest.sorted <- sort(rules_protest,decreasing = TRUE,by="lift")
plotly_arules(rules)
plotly_arules(rules_count)
plotly_arules(rules_protest)
inspect(rules.sorted[1:50])
inspect(subset(rules.sorted,subset=rhs %pin% "count=")[1:10])